import os
import logging
from flask import Flask, request, jsonify
from sqlalchemy import create_engine, text

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [MDM RECEIVER] - %(message)s')

app = Flask(__name__)

# Cloud Database Credentials
POSTGRES_API_URL = os.environ.get("POSTGRES_API_URL")
MYSQL_MASTER_URL = os.environ.get("MYSQL_MASTER_URL")

if not POSTGRES_API_URL or not MYSQL_MASTER_URL:
    logging.critical("Database URLs missing! Ensure environment variables are set.")
    exit(1)

# Create engines
pg_engine = create_engine(POSTGRES_API_URL, pool_size=5, max_overflow=10)
mysql_engine = create_engine(MYSQL_MASTER_URL, pool_size=5, max_overflow=10)

# --- UPTIMEROBOT HEALTH CHECK ---
@app.route('/', methods=['GET'])
def health_check():
    return "MDM Receiver is awake and listening!", 200

# --- HES CALLBACK ROUTE ---
@app.route('/api/v1/callbacks/hes-status', methods=['POST'])
def hes_status_callback():
    data = request.json
    
    hes_tx_id = data.get('hes_transaction_id')
    reference_id = data.get('reference_id') # The command_id generated by your engine
    meter_no = data.get('meter_no')
    command = data.get('command')           # 'DISCONNECT' or 'RECONNECT'
    
    # THE FIX: Check for 'status' first, fallback to 'execution_status'
    execution_status = data.get('status') or data.get('execution_status')
    
    logging.info(f"Received Callback: {command} for {meter_no} | Status: {execution_status}")
    
    if not execution_status:
        return jsonify({"error": "Missing status in payload"}), 400
    
    # 1. Update the tracking log in Neon PostgreSQL
    try:
        with pg_engine.begin() as pg_conn:
            pg_conn.execute(
                text("""
                    UPDATE dc_rc_log 
                    SET status = :status, 
                        hes_transaction_id = :hes_tx,
                        executed_at = NOW()
                    WHERE command_id = :cmd_id
                """),
                {"status": execution_status, "hes_tx": hes_tx_id, "cmd_id": reference_id}
            )
    except Exception as e:
        logging.error(f"PostgreSQL Update Failed: {e}")
        return jsonify({"error": "Failed to update tracking log"}), 500

    # 2. Update Physical State in Aiven MySQL Master
    if execution_status == "SUCCESS":
        # The RC/DC Dynamic Switch Logic
        if command == 'DISCONNECT':
            new_status = 'D'
        elif command == 'RECONNECT':
            new_status = 'C'
        else:
            return jsonify({"error": f"Unknown command type: {command}"}), 400
            
        try:
            with mysql_engine.begin() as mysql_conn:
                mysql_conn.execute(
                    text("""
                        UPDATE consumer_master 
                        SET connection_status = :new_status 
                        WHERE meter_no = :meter_no
                    """),
                    {"new_status": new_status, "meter_no": meter_no}
                )
            logging.info(f"✅ MySQL Master Updated. {meter_no} is now '{new_status}'.")
        except Exception as e:
            logging.error(f"MySQL Update Failed: {e}")
            return jsonify({"error": "Failed to update master table"}), 500

    return jsonify({"message": "Callback processed securely."}), 200

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)
